#!/bin/bash

# baseado no bldeznix109 (https://sourceforge.net/projects/eznixos/)

# fase 1 - setando as variaveis

SOURCE="$(pwd)"
DEST="$(pwd)/luanSantanaOS"

# fase 2 - criar as pastas mac do mac

mkdir $DEST
cd $DEST

# fase 3 - configurar os lek lá

lb config --bootappend-live "boot=live splash components username=luanete user-fullname=luanete" \
	--binary-images iso-hybrid --mode debian --architectures amd64 --linux-flavours amd64 \
	--distribution buster --archive-areas "main contrib non-free" --updates true --security true \
	--cache true --apt-recommends true --debian-installer live --debian-installer-gui true \
	--iso-volume luanSantanaOS --iso-application luanSantanaOS --iso-preparer adotDEV \
	--iso-publisher adotDEV-https://github.com/luanSantanaOS/luanSantanaOS \
	--mirror-chroot-security http://ftp.br.debian.org/debian-security/ \
	--mirror-bootstrap http://debian.pop-sc.rnp.br/debian/

# fase 4 - configurando os pacote

echo "task-xfce-desktop" > $DEST/config/package-lists/desktop.list.chroot

echo "grub-common grub2-common grub-pc-bin efibootmgr grub-efi-amd64 grub-efi-amd64-bin \
	grub-efi-amd64-signed grub-efi-ia32-bin libefiboot1 libefivar1 mokutil \
	shim-helpers-amd64-signed shim-signed-common shim-unsigned \
	" > $DEST/config/package-lists/grubuefi.list.binary


echo "calamares calamares-settings-debian xfce4-goodies plymouth plymouth-label haveged less orage gdebi galculator \
	grsync psensor gparted flac faad faac mjpegtools x265 x264 mpg321 vlc cdrdao \
	frei0r-plugins htop jfsutils xfsprogs ntfs-3g cdtool mtools gthumb xorriso \
	cdrskin p7zip-full p7zip-rar hardinfo inxi firefox-esr dialog papirus-icon-theme \
	rar unrar cifs-utils fuse gvfs-fuse gvfs-backends gvfs-bin pciutils squashfs-tools \
	syslinux syslinux-common dosfstools isolinux live-build fakeroot linux-headers-amd64 \
	lsb-release menu build-essential dkms curl wget iftop apt-transport-https dirmngr nvidia-detect \
	neofetch firmware-linux firmware-linux-nonfree firmware-misc-nonfree firmware-realtek firmware-atheros \
	firmware-bnx2 firmware-bnx2x firmware-brcm80211 firmware-ipw2x00 firmware-intelwimax firmware-iwlwifi \
	firmware-libertas firmware-netxen firmware-zd1211 gnome-nettool guvcview \
	" > $DEST/config/package-lists/packages.list.chroot

# fase 5 - configurando as pasta da iso

mkdir -p $DEST/config/includes.chroot/etc/skel/Desktop
echo luanOS > $DEST/config/includes.chroot/etc/hostname

cp -r $SOURCE/bootloaders $DEST/config/bootloaders
cp -r $SOURCE/desktop-base/* $DEST/config/includes.chroot/
cp -r $SOURCE/default-user/* $DEST/config/includes.chroot/
cp -r $SOURCE/backgrounds/* $DEST/config/includes.chroot/
cp -r $SOURCE/os-release/* $DEST/config/includes.chroot/
cp -r $SOURCE/calamares/* $DEST/config/includes.chroot/
cp -r $SOURCE/neofetch/* $DEST/config/includes.chroot/
cp -r $SOURCE/plymouth/* $DEST/config/includes.chroot/
cp -r $SOURCE/lightdm/* $DEST/config/includes.chroot/
cp -r $SOURCE/themes/* $DEST/config/includes.chroot/
cp -r $SOURCE/icons/* $DEST/config/includes.chroot/
cp -r $SOURCE/grub/* $DEST/config/includes.chroot/

# fase 6 - rock lee vs gaara (linkin park)

lb build

